spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/taskmanagement
  application:
    name: task-management-api
server:
  port: 8080
logging:
  level:
    com.example.taskmanagement: DEBUG
